### ISSUE TITLE
detect_advisor.exe file detected as Malicious 

### ISSUE THREAD

**Issue by barakharyati** [matthewb66/detect_advisor#1]
file detect_advisor.exe  detected as a Virus on several AV  and Sandbox Scan. 
Hash: 4831afbd4453f6f3da373cea91fd931fda7987c5778b66c7022706ca3833dc65
can you please verify if it false positive ( if it possible please add community information to VT) 

thank you  

Virus Total:
https://www.virustotal.com/gui/file/4831afbd4453f6f3da373cea91fd931fda7987c5778b66c7022706ca3833dc65/behavior/C2AE

hybrid-analysis:
https://www.hybrid-analysis.com/sample/4831afbd4453f6f3da373cea91fd931fda7987c5778b66c7022706ca3833dc65

**Comment by barakharyati** [comment]
please find also joes Analysis
https://www.joesandbox.com/analysis/512180

**Comment by matthewb66** [comment]
Hi

This demonstrates a generic issue of virus scanning.

The executable is not malicious.

It has been built using the pyinstaller package, and there are probably
some other malicious executables which have been built the same way then
added to some virus fingerprint databases, but catching all similarly built
programs.

I have temporarily removed the Windows executable from the repo as I am
unsure how to fix the virus checkers.

Thanks

**Comment by barakharyati** [comment]
thank you
