### ISSUE TITLE
Update detect command to use detect8.sh

### ISSUE THREAD

**Issue by fdavis99** [matthewb66/detect_advisor#2]
Synopsys has long ago updated detect to detect7 and now detect8. The DETECT COMMAND output should be:
bash <(curl -s -L https://detect.synopsys.com/detect8.sh)

**Comment by matthewb66** [comment]
This repository has not been maintained for a long time.

**Comment by fdavis99** [comment]
Sorry to hear -- it seems pretty useful. Thanks for letting us know.
